# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://docs.github.com/en/github/administering-a-repository/customizing-dependency-updates

version: 2
updates:
    # --- GitHub Actions
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'

    - package-ecosystem: 'npm'
      directory: '/'
      open-pull-requests-limit: 20
      rebase-strategy: 'auto'
      schedule:
          interval: 'monthly'
      allow:
          - dependency-type: 'direct'
      ignore:
          - dependency-name: 'typescript'
            versions: ['4.x']
          - dependency-name: '@types/node'
          # esbuild: version 0.17.x needs update to the watch option as described here. 
          #     After updating the code, there is still an issue with debugging in VS Code - 'esbuild problem matcher' extension is not updated yet
          - dependency-name: 'esbuild'
          # esbuild-sass-plugin: version 2.6.0 throws an error that sass module was not found
          - dependency-name: 'esbuild-sass-plugin'
          # react-router-dom: version 6.8.2 throws an error with the current code
          - dependency-name: 'react-router-dom'
          # esbuild-css-modules-plugin: version 2.7.1 seems to only work with node v16 onwards
          - dependency-name: 'esbuild-css-modules-plugin'
